/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'
import { Route as EventsNewRouteImport } from './routes/events.new'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$username': typeof UUsernameRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$username': typeof UUsernameRoute
  '/events': typeof EventsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$username': typeof UUsernameRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/events/new'
    | '/groups/$slug'
    | '/messages/$userId'
    | '/tag/$tag'
    | '/u/$username'
    | '/events/'
    | '/groups/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/events/new'
    | '/groups/$slug'
    | '/messages/$userId'
    | '/tag/$tag'
    | '/u/$username'
    | '/events'
    | '/groups'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/events/new'
    | '/groups/$slug'
    | '/messages/$userId'
    | '/tag/$tag'
    | '/u/$username'
    | '/events/'
    | '/groups/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  EventsNewRoute: typeof EventsNewRoute
  GroupsSlugRoute: typeof GroupsSlugRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  TagTagRoute: typeof TagTagRoute
  UUsernameRoute: typeof UUsernameRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  EventsNewRoute: EventsNewRoute,
  GroupsSlugRoute: GroupsSlugRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  TagTagRoute: TagTagRoute,
  UUsernameRoute: UUsernameRoute,
  EventsIndexRoute: EventsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
